package com.scm.entities;

public enum AuthProviders {
    SELF, GOOGLE, FACEBOOK, TWITTER, LINKEDIN, GITHUB, APPLE, MICROSOFT, AMAZON, INSTAGRAM, DISCORD, SLACK, SPOTIFY, TWITCH, YAHOO, ORCID, REDDIT, VKONTAKTE, WECHAT, QQ, BAIDU, ALIBABA, TENCENT, LINE, KAKAO_TALK, PAYPAL, STRIPE
}
